### ISSUE TITLE
Threading/Forking Servers

### ISSUE THREAD

**Issue by Ksengine** [pybee/ouroboros#26]
Its better if ouroboros has 
- ThreadingHTTPServer
- ForkingHTTPServer
- ThreadingWSGIServer
- ForkingWSGIServer

Threading servers handles each request on thread.
Forking servers handles each request on new process.
They are useful. But not provided by stdlib.
Many external server frameworks are providing them.

I can add these servers with few lines.
Can i make a pr

**Comment by freakboy3742** [comment]
The aim of Ouroboros is not to be a utility library of "useful" content. It aims to be an implementation of the Python standard library.

I am, at this point, *begging* you to slow down, engage with the community as a whole, and *focus on one thing at a time*. I am not enjoying the experience of responding to dozens of 2 line, inadequately explained tickets that ignore years of project context.

You came to the BeeWare project asking about a Qt backend. You started work on that backend, but haven't touched it in days. However, you *have* submitted issues and PRs for GTK and Windows, and made numerous suggestions that are either in conflict with the goals of the BeeWare project, or have been in active discussion within the project in recent weeks and months. *Please* slow down, narrow your focus, engage with the community, and focus on the quality of your communication, rather than the volume of contributions.
